/**
 * Per-locale copy for marketing landing + pricing.
 *
 * Strict separation: each locale's strings contain ONLY that locale's
 * language. No cross-language pollution.
 *
 * - en       English-only (brand "KIEIO" + (o) mark stay)
 * - zhHant   繁體中文 · HK Cantonese voice (founder's natural register)
 * - zhHans   简体中文 · Mandarin formal
 *
 * Brand name "KIEIO" + the typographic mark "(o)" remain unchanged
 * across locales — they are the product identity, not translatable copy.
 *
 * Chat preview dialogue: per-locale showcase of what THAT user would
 * experience. EN visitors see English NPC chat; zhHant Cantonese;
 * zhHans Mandarin. The "Bilingual" section in the landing still mixes
 * languages because it's a literal demonstration of multilingual support.
 */

export type MarketingLang = "en" | "zhHant" | "zhHans";

export const MARKETING_COPY = {
  // ─── NAV ───────────────────────────────────────────
  nav: {
    en: { how: "How it works", memory: "Memory", pricing: "Pricing", bilingual: "Languages", begin: "Begin" },
    zhHant: { how: "點玩", memory: "記憶", pricing: "訂價", bilingual: "語言", begin: "立即開始" },
    zhHans: { how: "怎么玩", memory: "记忆", pricing: "订价", bilingual: "语言", begin: "立即开始" },
  },

  // ─── HERO ──────────────────────────────────────────
  hero: {
    en: {
      eyebrow: "AI Interactive Story RPG",
      titleLine1: "Write a line.",
      titleLine2Pre: "Live a ",
      titleAccent: "life",
      titleSuffix: ".",
      zhTagLine1: "Turn one sentence into a world.",
      zhTagLine2Pre: "AI ",
      zhTagPop: "writes",
      zhTagLine2Post: " the story with you.",
      sub: "KIEIO turns one sentence into a world, a cast, and a life you can step into. NPCs that remember 200+ turns. First story always free.",
      ctaPrimary: "Begin your first life →",
      ctaSecondary: "See how it works",
      meta1: "200+ turn memory",
      meta2: "Cantonese · Traditional Chinese",
      meta3: "Free to start",
      previewTitle: "The Inn at Midnight · Live",
      previewTurn: "turn 1 / ∞",
      previewInputHint: "What do you say to the innkeeper?",
      // English NPC dialogue
      chat: {
        m1Who: "Innkeeper · Mei",
        m1Text: "The inn smells of cold tea and damp wool. Mei sets down her ledger, looks at you.",
        m1Quote: "You're",
        m1QuoteEm: "late",
        m1QuotePost: ".",
        m2Who: "You",
        m2Text: "“Sorry. The river was higher than I expected.”",
        m3Who: "Innkeeper · Mei",
        m3Text: "Her brow tightens, then softens. “You said that last time.” She slides a bowl of hot tea across the counter.",
        m3Mem: "Mei remembers · trust −4 · turn 87 line",
        m4Who: "Narrator",
        m4Text: "She has been waiting. You are not as forgotten as you hoped.",
      },
    },
    zhHant: {
      eyebrow: "AI 互動式故事 RPG · 中文圈",
      titleLine1: "寫一句說話。",
      titleLine2Pre: "活出一段",
      titleAccent: "人生",
      titleSuffix: "。",
      zhTagLine1: "由一個 idea 開始，",
      zhTagLine2Pre: "同 AI ",
      zhTagPop: "一齊",
      zhTagLine2Post: "講你嘅故事。",
      sub: "KIEIO 用一句說話幫你 build 起一個世界、一班角色、一段你可以行入去嘅人生。NPC 記得你 200+ 個 turn 嘅嘢。第一段故事永遠免費。",
      ctaPrimary: "開始第一段人生 →",
      ctaSecondary: "睇下點玩",
      meta1: "200+ turn 記憶",
      meta2: "繁中 · 廣東話",
      meta3: "免費玩",
      previewTitle: "深夜客棧 · 即時",
      previewTurn: "turn 1 / ∞",
      previewInputHint: "你會點答阿美？",
      chat: {
        m1Who: "阿美 · 掌櫃",
        m1Text: "客棧聞到冷茶同濕羊毛嘅味。阿美放低本帳簿，望住你。",
        m1Quote: "「你",
        m1QuoteEm: "遲咗",
        m1QuotePost: "。」",
        m2Who: "你",
        m2Text: "「對唔住，條河比預期高。」",
        m3Who: "阿美 · 掌櫃",
        m3Text: "佢嘅眉皺咗一陣，然後鬆開。「上次你都係咁講。」佢遞返一碗熱茶過嚟。",
        m3Mem: "阿美記得 · trust −4 · 第 87 回合對白",
        m4Who: "敘事者",
        m4Text: "佢一直喺度等緊你。原來你冇你想像中咁被人忘記。",
      },
    },
    zhHans: {
      eyebrow: "AI 互动式故事 RPG · 中文圈",
      titleLine1: "写一句话。",
      titleLine2Pre: "活出一段",
      titleAccent: "人生",
      titleSuffix: "。",
      zhTagLine1: "由一个想法开始，",
      zhTagLine2Pre: "和 AI ",
      zhTagPop: "一起",
      zhTagLine2Post: "讲你的故事。",
      sub: "KIEIO 用一句话帮你构建一个世界、一群角色、一段你可以走进去的人生。NPC 记得你 200+ 个 turn 的事。第一段故事永远免费。",
      ctaPrimary: "开始第一段人生 →",
      ctaSecondary: "看怎么玩",
      meta1: "200+ turn 记忆",
      meta2: "简中 · 繁中",
      meta3: "免费开始",
      previewTitle: "深夜客栈 · 实时",
      previewTurn: "turn 1 / ∞",
      previewInputHint: "你会怎么回答阿美？",
      chat: {
        m1Who: "阿美 · 掌柜",
        m1Text: "客栈里飘着冷茶和湿羊毛的味道。阿美放下账簿，看着你。",
        m1Quote: "「你",
        m1QuoteEm: "迟到了",
        m1QuotePost: "。」",
        m2Who: "你",
        m2Text: "「对不起，河水比预期高。」",
        m3Who: "阿美 · 掌柜",
        m3Text: "她眉头皱了一下，又松开。「上次你也是这么说。」她把一碗热茶推过来。",
        m3Mem: "阿美记得 · trust −4 · 第 87 回合对白",
        m4Who: "叙述者",
        m4Text: "她一直在等。原来你没你想像中那么被人遗忘。",
      },
    },
  },

  // ─── STREAM ────────────────────────────────────────
  stream: {
    en: {
      eyebrow: "Stories · Community plays right now",
      titleLine1: "One folder.",
      titleAccent: "A million lives.",
      sub: "Stories from the global KIEIO community",
      folderLabelEn: "Stories",
      folderLabelZh: "Stories",
    },
    zhHant: {
      eyebrow: "故事 · 社區而家玩緊",
      titleLine1: "一個資料夾。",
      titleAccent: "百萬個人生。",
      sub: "嚟自 KIEIO 全球社區嘅故事",
      folderLabelEn: "Stories",
      folderLabelZh: "故事",
    },
    zhHans: {
      eyebrow: "故事 · 社区正在玩",
      titleLine1: "一个文件夹。",
      titleAccent: "百万种人生。",
      sub: "来自 KIEIO 全球社区的故事",
      folderLabelEn: "Stories",
      folderLabelZh: "故事",
    },
  },

  // ─── HOW IT WORKS ──────────────────────────────────
  how: {
    en: {
      eyebrow: "How it works",
      titleLine1: "Three steps.",
      titleLine2: "One life.",
      lead: "You write a single line. KIEIO builds a world from it. NPCs arrive — with memory, with opinions, with their own agendas. The story remembers you back.",
      step1Title: "Write a seed",
      step1Detail: "A line, a paragraph, a premise. “An inn at midnight. The keeper studies a stranger.” That's enough.",
      step2Title: "Enter the world",
      step2Detail: "KIEIO renders a place, populates it, and hands you the protagonist. The narrator listens before they speak.",
      step3Title: "Live a life",
      step3Detail: "Speak, act, choose. Every consequence is weighed. NPCs remember. The world bends around what you've done.",
      panel1Tag: "Step 01 · Seed",
      panel1En: "An inn at midnight. The keeper studies a stranger who arrived too late.",
      panel1Zh: "",
      panel2Tag: "Step 02 · World",
      panel2En: "The inn smells of cold tea and damp wool. Mei sets down her ledger. The rain hasn't let up in three days. “You're late,” she says. She doesn't ask your name.",
      panel2Zh: "",
      panel3Tag: "Step 03 · Choose",
      panel3Narrate: "Mei is waiting. The fire crackles. What do you say?",
      panel3Choice1: "“I'm sorry. The river was higher than I expected.”",
      panel3Choice2: "Sit down without answering. Let the silence speak.",
      panel3Choice3: "“Do you remember me, Mei?”",
      panel3Mem: "Mei remembers · trust +12 · turn 1 of ∞",
    },
    zhHant: {
      eyebrow: "點玩",
      titleLine1: "三步。",
      titleLine2: "一段人生。",
      lead: "你寫一句說話。KIEIO 由嗰句說話 build 起一個世界。NPC 會出現 — 有記憶、有立場、有自己嘅 agenda。個故事會反過嚟記住你。",
      step1Title: "寫一粒種子",
      step1Detail: "一句、一段、一個前提。「客棧。半夜。掌櫃望住一個遲到嘅陌生人。」夠晒。",
      step2Title: "行入個世界",
      step2Detail: "KIEIO render 個地方、放入啲角色、把主角交俾你。敘事者會聽你講先,先答。",
      step3Title: "活一段人生",
      step3Detail: "講嘢、行動、揀。每個後果都有重量。NPC 會記得。個世界會跟你做過嘅嘢變化。",
      panel1Tag: "第 01 步 · 種子",
      panel1En: "An inn at midnight. The keeper studies a stranger who arrived too late.",
      panel1Zh: "客棧。半夜。掌櫃望住一個遲到嘅陌生人。",
      panel2Tag: "第 02 步 · 世界",
      panel2En: "",
      panel2Zh: "客棧聞到冷茶同濕羊毛嘅味。阿美放低本帳簿。雨已經落咗三日。「你遲咗。」佢冇問你個名。",
      panel3Tag: "第 03 步 · 揀",
      panel3Narrate: "阿美喺度等緊。爐火劈啪。你會點答？",
      panel3Choice1: "「對唔住。條河比預期高。」",
      panel3Choice2: "唔出聲，坐低先。等沉默講嘢。",
      panel3Choice3: "「阿美，你仲記唔記得我？」",
      panel3Mem: "阿美記得 · trust +12 · turn 1 of ∞",
    },
    zhHans: {
      eyebrow: "怎么玩",
      titleLine1: "三步。",
      titleLine2: "一段人生。",
      lead: "你写一句话。KIEIO 由那句话开始构建一个世界。NPC 出场 — 有记忆、有立场、有自己的目标。故事会反过来记住你。",
      step1Title: "写下一颗种子",
      step1Detail: "一句、一段、一个前提。「客栈。半夜。掌柜看着一个迟到的陌生人。」就够了。",
      step2Title: "走进那个世界",
      step2Detail: "KIEIO 渲染场景、放入角色、把主角交给你。叙述者会先听你说，再回答。",
      step3Title: "活一段人生",
      step3Detail: "说话、行动、选择。每个后果都有重量。NPC 会记得。世界会跟你做过的事而改变。",
      panel1Tag: "第 01 步 · 种子",
      panel1En: "An inn at midnight. The keeper studies a stranger who arrived too late.",
      panel1Zh: "客栈。半夜。掌柜看着一个迟到的陌生人。",
      panel2Tag: "第 02 步 · 世界",
      panel2En: "",
      panel2Zh: "客栈飘着冷茶和湿羊毛的味道。阿美放下账簿。雨已经下了三天。「你迟到了。」她没问你的名字。",
      panel3Tag: "第 03 步 · 选择",
      panel3Narrate: "阿美在等。炉火劈啪作响。你会怎么回答？",
      panel3Choice1: "「对不起。河水比预期高。」",
      panel3Choice2: "不出声，先坐下。让沉默说话。",
      panel3Choice3: "「阿美，你还记得我吗？」",
      panel3Mem: "阿美记得 · trust +12 · turn 1 of ∞",
    },
  },

  // ─── MEMORY ────────────────────────────────────────
  memory: {
    en: {
      eyebrow: "Memory architecture",
      titlePre: "NPCs ",
      titleAccent: "remember",
      titleSuffix: ".",
      lede: "Not the last three messages. Not a shallow cache. KIEIO uses a four-layer memory system that holds what you've done, who you've hurt, who you've loved — for two hundred turns and beyond.",
      card1Tag: "Layer 01 · Episodic",
      card1Title: "What just happened",
      card1Body: "The last few exchanges. Tone, mood, the immediate beat. Resolves “Mei looks at you” without asking who Mei is.",
      card1Turn: "turn 247 — recall 100%",
      card2Tag: "Layer 02 · Semantic",
      card2Title: "Who is who",
      card2Body: "Names, relationships, the shape of the world. Mei is the innkeeper. The river floods every spring. You are a courier who lost something.",
      card2Turn: "turn 247 — recall 96%",
      card3Tag: "Layer 03 · Emotional",
      card3Title: "How they feel",
      card3Body: "Trust, suspicion, affection, grudges. NPCs carry their emotional state forward. They will hold a grudge for two hundred turns.",
      card3Turn: "turn 247 — Mei trust 38/100",
    },
    zhHant: {
      eyebrow: "記憶架構",
      titlePre: "NPC ",
      titleAccent: "會記得",
      titleSuffix: "。",
      lede: "唔係淨係記得頭三句。唔係淺嘅 cache。KIEIO 用四層記憶系統,記住你做過咩、傷害過邊個、愛過邊個 — 200 個 turn 之外都記得。",
      card1Tag: "第 01 層 · 即時",
      card1Title: "啱啱發生過",
      card1Body: "最近幾句對話。語氣、氣氛、即場節奏。「阿美望住你」唔使再解釋阿美係邊個。",
      card1Turn: "turn 247 — 回憶 100%",
      card2Tag: "第 02 層 · 知識",
      card2Title: "邊個係邊個",
      card2Body: "名、關係、世界嘅形狀。阿美係掌櫃。條河每年春天會浸。你係送嘢嘅 courier,失咗啲嘢。",
      card2Turn: "turn 247 — 回憶 96%",
      card3Tag: "第 03 層 · 情感",
      card3Title: "佢哋點 feel",
      card3Body: "信任、懷疑、好感、仇恨。NPC 會帶住情緒繼續行。佢可以記恨足 200 個 turn。",
      card3Turn: "turn 247 — 阿美 trust 38/100",
    },
    zhHans: {
      eyebrow: "记忆架构",
      titlePre: "NPC ",
      titleAccent: "记得",
      titleSuffix: "。",
      lede: "不是只记得最近三句。也不是浅的 cache。KIEIO 用四层记忆系统记住你做过什么、伤害过谁、爱过谁 — 200 个 turn 之后仍然记得。",
      card1Tag: "第 01 层 · 即时",
      card1Title: "刚刚发生的事",
      card1Body: "最近几次对话。语气、氛围、即场节奏。「阿美看着你」不用再解释阿美是谁。",
      card1Turn: "turn 247 — 回忆 100%",
      card2Tag: "第 02 层 · 知识",
      card2Title: "谁是谁",
      card2Body: "名字、关系、世界的样子。阿美是掌柜。河水每年春天会泛滥。你是个送货员，丢了点东西。",
      card2Turn: "turn 247 — 回忆 96%",
      card3Tag: "第 03 层 · 情感",
      card3Title: "他们怎么想",
      card3Body: "信任、怀疑、好感、仇恨。NPC 会带着情绪继续走。他可以记仇整整 200 个 turn。",
      card3Turn: "turn 247 — 阿美 trust 38/100",
    },
  },

  // ─── BILINGUAL / LANGUAGES ─────────────────────────
  bilingual: {
    en: {
      eyebrow: "Built for the Chinese-speaking world",
      titlePre: "Cantonese, ",
      titlePop: "Traditional",
      titleMid: ", Simplified — ",
      titleSuffix: "native.",
      p1: "KIEIO speaks Cantonese, Traditional Chinese, Mandarin — properly. NPCs have their own emotions and personality. They remember what you've done. They push back, forgive, and hold a grudge.",
      p2: "Every story belongs to you alone. Every NPC lives for you.",
      stat1Num: "繁中",
      stat1Label: "Traditional · default",
      stat2Num: "廣東話",
      stat2Label: "Cantonese · native",
      stat3Num: "200+",
      stat3Label: "turns of memory",
      stat4Num: "∞",
      stat4Label: "stories per seed",
    },
    zhHant: {
      eyebrow: "為中文圈而做",
      titlePre: "用",
      titlePop: "廣東話",
      titleMid: "",
      titleSuffix: "講你嘅故事",
      p1: "KIEIO 嘅 NPC 識講廣東話、繁中、普通話 — 同你講人話。會有自己嘅情緒同性格。記得你做過嘅嘢。會反駁你,會原諒你,會記住。",
      p2: "每一個故事都係屬於你一個人。每一個 NPC 都係為你而活。",
      stat1Num: "繁中",
      stat1Label: "繁體中文 · 預設",
      stat2Num: "廣東話",
      stat2Label: "廣東話 · 母語",
      stat3Num: "200+",
      stat3Label: "turn 記憶",
      stat4Num: "∞",
      stat4Label: "種子變故事",
    },
    zhHans: {
      eyebrow: "为中文圈而做",
      titlePre: "用",
      titlePop: "中文",
      titleMid: "",
      titleSuffix: "讲你的故事",
      p1: "KIEIO 的 NPC 会讲普通话、简中、繁中、广东话 — 跟你说人话。有自己的情绪和性格。记得你做过的事。会反驳你、会原谅你、会记住。",
      p2: "每一个故事都是属于你一个人。每一个 NPC 都是为你而活。",
      stat1Num: "简中",
      stat1Label: "简体中文 · 母语",
      stat2Num: "普通话",
      stat2Label: "Mandarin · 原生",
      stat3Num: "200+",
      stat3Label: "turn 记忆",
      stat4Num: "∞",
      stat4Label: "种子变故事",
    },
  },

  // ─── ADULT ─────────────────────────────────────────
  adult: {
    en: {
      eyebrow: "Mature content · opt-in",
      titleLine1: "Adult stories,",
      titleLine2: "handled with maturity.",
      p: "KIEIO supports mature themes — but only behind age verification. We use Stripe Identity for one-time KYC. Verify once, unlock for good. Off by default. Never the front page.",
      zhSub: "",
      pill1: "Opt-in only",
      pill2: "KYC verified",
      pill3: "Off by default",
      pill4: "No surprises",
    },
    zhHant: {
      eyebrow: "成人內容 · 自主開啟",
      titleLine1: "成人故事,",
      titleLine2: "認真處理。",
      p: "KIEIO 支援成人題材 — 但要先做年齡驗證。我哋用 Stripe Identity 一次過 KYC。驗證一次,永久解鎖。預設關閉。永遠唔會出現喺首頁。",
      zhSub: "",
      pill1: "自主選擇",
      pill2: "KYC 驗證",
      pill3: "預設關閉",
      pill4: "唔會突襲",
    },
    zhHans: {
      eyebrow: "成人内容 · 自主开启",
      titleLine1: "成人故事，",
      titleLine2: "认真处理。",
      p: "KIEIO 支持成人题材 — 但需要先做年龄验证。我们用 Stripe Identity 一次性 KYC。验证一次，永久解锁。默认关闭。永远不会出现在首页。",
      zhSub: "",
      pill1: "自主选择",
      pill2: "KYC 验证",
      pill3: "默认关闭",
      pill4: "无突袭",
    },
  },

  // ─── CTA ───────────────────────────────────────────
  cta: {
    en: {
      titleLine1: "Begin your",
      titleAccent: "first life",
      titleSuffix: ".",
      ledeLine1: "The first story is always free.",
      ledeLine2: "",
      ctaPrimary: "Begin your adventure →",
      ctaSecondary: "Browse the library",
    },
    zhHant: {
      titleLine1: "開始你嘅",
      titleAccent: "第一段人生",
      titleSuffix: "。",
      ledeLine1: "第一段故事永遠係免費。",
      ledeLine2: "",
      ctaPrimary: "開始冒險 →",
      ctaSecondary: "睇下故事庫",
    },
    zhHans: {
      titleLine1: "开始你的",
      titleAccent: "第一段人生",
      titleSuffix: "。",
      ledeLine1: "第一段故事永远免费。",
      ledeLine2: "",
      ctaPrimary: "开始冒险 →",
      ctaSecondary: "看故事库",
    },
  },

  // ─── SCROLL / MISC ─────────────────────────────────
  misc: {
    en: { scroll: "Scroll" },
    zhHant: { scroll: "向下捲" },
    zhHans: { scroll: "向下滚" },
  },
};

// ─── Locale switcher labels (always show all three native names) ─────
export const LOCALE_SWITCHER = [
  { lang: "zhHant" as const, label: "繁中", locale: "zh-Hant" },
  { lang: "zhHans" as const, label: "简中", locale: "zh-Hans" },
  { lang: "en" as const, label: "EN", locale: "en" },
];

/** Map next-intl locale code → MarketingLang key. */
export function langFromLocale(locale: string): MarketingLang {
  if (locale.startsWith("en")) return "en";
  if (locale.toLowerCase().includes("hans") || locale === "zh-CN") return "zhHans";
  return "zhHant";
}
